version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-ai_learning_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ai_learning_password}
      POSTGRES_DB: ${POSTGRES_DB:-ai_learning_platform}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ai-learning-network

  # pgAdmin (optional - for database management)
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ailearning.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - ai-learning-network
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:

networks:
  ai-learning-network:
    driver: bridge
